export interface LocalMovie {
  id: string;
  imdbID: string;
  Title: string;
  Year: string;
  Rated: string;
  Released: string;
  Runtime: string;
  Genre: string;
  Director: string;
  Writer: string;
  Actors: string;
  Plot: string;
  Language: string;
  Country: string;
  Awards: string;
  Poster: string;
  Ratings: { Source: string; Value: string }[];
  Metascore: string;
  imdbRating: string;
  imdbVotes: string;
  Type: string;
  DVD?: string;
  BoxOffice?: string;
  Production?: string;
}

export const LOCAL_MOVIES: LocalMovie[] = [
  // === ACTION ===
  { id: 'tt0133093', imdbID: 'tt0133093', Title: 'The Matrix', Year: '1999', Rated: 'R', Released: '31 Mar 1999', Runtime: '136 min', Genre: 'Action, Sci-Fi', Director: 'Lana Wachowski, Lilly Wachowski', Writer: 'Lilly Wachowski, Lana Wachowski', Actors: 'Keanu Reeves, Laurence Fishburne, Carrie-Anne Moss', Plot: 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth — the life he knows is the elaborate deception of an evil cyber-intelligence.', Language: 'English', Country: 'USA, Australia', Awards: 'Won 4 Oscars. 42 wins & 51 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BN2NmN2VhMTQtMDNiOS00NDlhLTliMjgtODE2ZTY0ODQyNDRhXkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.7/10' }], Metascore: '73', imdbRating: '8.7', imdbVotes: '2,050,000', Type: 'movie' },
  { id: 'tt0468569', imdbID: 'tt0468569', Title: 'The Dark Knight', Year: '2008', Rated: 'PG-13', Released: '18 Jul 2008', Runtime: '152 min', Genre: 'Action, Crime, Drama', Director: 'Christopher Nolan', Writer: 'Jonathan Nolan, Christopher Nolan', Actors: 'Christian Bale, Heath Ledger, Aaron Eckhart', Plot: 'When a menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological tests of his ability to fight injustice.', Language: 'English', Country: 'USA, UK', Awards: 'Won 2 Oscars. 159 wins & 163 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_QL75_UX380_CR0,0,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '9.0/10' }], Metascore: '84', imdbRating: '9.0', imdbVotes: '2,900,000', Type: 'movie' },
  { id: 'tt0167260', imdbID: 'tt0167260', Title: 'The Lord of the Rings: The Return of the King', Year: '2003', Rated: 'PG-13', Released: '17 Dec 2003', Runtime: '201 min', Genre: 'Action, Adventure, Drama', Director: 'Peter Jackson', Writer: 'J.R.R. Tolkien, Fran Walsh, Philippa Boyens', Actors: 'Elijah Wood, Viggo Mortensen, Ian McKellen', Plot: "Gandalf and Aragorn lead the World of Men against Sauron's army to draw his gaze from Frodo and Sam as they approach Mount Doom with the One Ring.", Language: 'English', Country: 'New Zealand, USA', Awards: 'Won 11 Oscars. 201 wins & 121 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BMTZkMjBjNWMtZGI5OC00MGU0LTk4ZTItODg2NWM3NTVmNWQ4XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '9.0/10' }], Metascore: '94', imdbRating: '9.0', imdbVotes: '2,000,000', Type: 'movie' },
  { id: 'tt0120737', imdbID: 'tt0120737', Title: 'The Lord of the Rings: The Fellowship of the Ring', Year: '2001', Rated: 'PG-13', Released: '19 Dec 2001', Runtime: '178 min', Genre: 'Action, Adventure, Drama', Director: 'Peter Jackson', Writer: 'J.R.R. Tolkien, Fran Walsh, Philippa Boyens', Actors: 'Elijah Wood, Ian McKellen, Orlando Bloom', Plot: "A meek Hobbit from the Shire and eight companions set out on a journey to destroy the powerful One Ring and save Middle-earth from the Dark Lord Sauron.", Language: 'English', Country: 'New Zealand, USA', Awards: 'Won 4 Oscars. 121 wins & 126 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BNzIxMDQ2YTctNDY4MC00ZTRhLTk4ODQtMTVlOWY4NTdiYmMwXkEyXkFqcGc@._V1_QL75_UX380_CR0,1,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.8/10' }], Metascore: '92', imdbRating: '8.8', imdbVotes: '2,000,000', Type: 'movie' },
  { id: 'tt0167261', imdbID: 'tt0167261', Title: 'The Lord of the Rings: The Two Towers', Year: '2002', Rated: 'PG-13', Released: '18 Dec 2002', Runtime: '179 min', Genre: 'Action, Adventure, Drama', Director: 'Peter Jackson', Writer: 'J.R.R. Tolkien, Fran Walsh, Philippa Boyens', Actors: 'Elijah Wood, Ian McKellen, Viggo Mortensen', Plot: "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.", Language: 'English', Country: 'New Zealand, USA', Awards: 'Won 2 Oscars. 132 wins & 135 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BMGQxMDdiOWUtYjc1Ni00YzM1LWE2NjMtZTg3Y2JkMjEzMTJjXkEyXkFqcGc@._V1_QL75_UX380_CR0,14,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.8/10' }], Metascore: '87', imdbRating: '8.8', imdbVotes: '1,900,000', Type: 'movie' },
  { id: 'tt0120689', imdbID: 'tt0120689', Title: 'The Green Mile', Year: '1999', Rated: 'R', Released: '10 Dec 1999', Runtime: '189 min', Genre: 'Crime, Drama, Fantasy', Director: 'Frank Darabont', Writer: 'Stephen King, Frank Darabont', Actors: 'Tom Hanks, David Morse, Michael Clarke Duncan', Plot: 'The lives of guards on death row are affected by one of their charges: a gentle giant with a mysterious gift.', Language: 'English', Country: 'USA', Awards: 'Nominated for 4 Oscars. 11 wins & 23 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BMTUxMzQyNjA5MF5BMl5BanBnXkFtZTYwOTU2NTY3._V1_QL75_UX380_CR0,0,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.6/10' }], Metascore: '61', imdbRating: '8.6', imdbVotes: '1,300,000', Type: 'movie' },
  { id: 'tt0110912', imdbID: 'tt0110912', Title: 'Pulp Fiction', Year: '1994', Rated: 'R', Released: '14 Oct 1994', Runtime: '154 min', Genre: 'Crime, Drama', Director: 'Quentin Tarantino', Writer: 'Quentin Tarantino, Roger Avary', Actors: 'John Travolta, Uma Thurman, Samuel L. Jackson', Plot: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.', Language: 'English', Country: 'USA', Awards: 'Won 1 Oscar. 70 wins & 75 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BYTViYTE3ZGQtNDBlMC00ZTAyLTkyODMtZGRiZDg0MjA2YThkXkEyXkFqcGc@._V1_QL75_UY562_CR3,0,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.9/10' }], Metascore: '95', imdbRating: '8.9', imdbVotes: '2,300,000', Type: 'movie' },
  { id: 'tt0111161', imdbID: 'tt0111161', Title: 'The Shawshank Redemption', Year: '1994', Rated: 'R', Released: '14 Oct 1994', Runtime: '142 min', Genre: 'Drama', Director: 'Frank Darabont', Writer: 'Stephen King, Frank Darabont', Actors: 'Tim Robbins, Morgan Freeman, Bob Gunton', Plot: 'Over the course of several years, two convicts form a friendship, seeking consolation and, eventually, redemption through basic compassion.', Language: 'English', Country: 'USA', Awards: 'Nominated for 7 Oscars. 21 wins & 43 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BMDAyY2FhYjctNDc5OS00MDNlLThiMGUtY2UxYWVkNGY2ZjljXkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '9.3/10' }], Metascore: '82', imdbRating: '9.3', imdbVotes: '3,000,000', Type: 'movie' },
  { id: 'tt0068646', imdbID: 'tt0068646', Title: 'The Godfather', Year: '1972', Rated: 'R', Released: '24 Mar 1972', Runtime: '175 min', Genre: 'Crime, Drama', Director: 'Francis Ford Coppola', Writer: 'Mario Puzo, Francis Ford Coppola', Actors: 'Marlon Brando, Al Pacino, James Caan', Plot: 'Don Vito Corleone, head of a mafia family, decides to hand over his empire to his youngest son Michael. However, his decision unintentionally puts the lives of his loved ones in grave danger.', Language: 'English, Italian, Latin', Country: 'USA', Awards: 'Won 3 Oscars. 31 wins & 30 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_QL75_UY562_CR8,0,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '9.2/10' }], Metascore: '100', imdbRating: '9.2', imdbVotes: '2,000,000', Type: 'movie' },
  { id: 'tt0071562', imdbID: 'tt0071562', Title: 'The Godfather Part II', Year: '1974', Rated: 'R', Released: '20 Dec 1974', Runtime: '202 min', Genre: 'Crime, Drama', Director: 'Francis Ford Coppola', Writer: 'Francis Ford Coppola, Mario Puzo', Actors: 'Al Pacino, Robert De Niro, Robert Duvall', Plot: 'The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.', Language: 'English, Italian, Spanish', Country: 'USA', Awards: 'Won 6 Oscars. 16 wins & 21 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BMDIxMzBlZDktZjMxNy00ZGI4LTgxNDEtYWRlNzRjMjJmOGQ1XkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '9.0/10' }], Metascore: '85', imdbRating: '9.0', imdbVotes: '1,300,000', Type: 'movie' },
  { id: 'tt1375666', imdbID: 'tt1375666', Title: 'Inception', Year: '2010', Rated: 'PG-13', Released: '16 Jul 2010', Runtime: '148 min', Genre: 'Action, Adventure, Sci-Fi', Director: 'Christopher Nolan', Writer: 'Christopher Nolan', Actors: 'Leonardo DiCaprio, Joseph Gordon-Levitt, Elliot Page', Plot: 'A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.', Language: 'English', Country: 'USA, UK', Awards: 'Won 4 Oscars. 157 wins & 220 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BMjAxMzY3NjcxNF5BMl5BanBnXkFtZTcwNTI5OTM0Mw@@._V1_QL75_UX380_CR0,0,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.8/10' }], Metascore: '74', imdbRating: '8.8', imdbVotes: '2,400,000', Type: 'movie' },
  { id: 'tt0137523', imdbID: 'tt0137523', Title: 'Fight Club', Year: '1999', Rated: 'R', Released: '15 Oct 1999', Runtime: '139 min', Genre: 'Drama', Director: 'David Fincher', Writer: 'Chuck Palahniuk, Jim Uhls', Actors: 'Brad Pitt, Edward Norton, Helena Bonham Carter', Plot: 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.', Language: 'English', Country: 'USA, Germany', Awards: 'Nominated for 1 Oscar. 11 wins & 38 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BOTgyOGQ1NDItNGU3Ny00MjU3LTg2YWEtNmEyYjBiMjI1Y2M5XkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.8/10' }], Metascore: '66', imdbRating: '8.8', imdbVotes: '2,300,000', Type: 'movie' },

  // === SCIENCE FICTION ===
  { id: 'tt0062622', imdbID: 'tt0062622', Title: '2001: A Space Odyssey', Year: '1968', Rated: 'G', Released: '02 Apr 1968', Runtime: '149 min', Genre: 'Adventure, Sci-Fi', Director: 'Stanley Kubrick', Writer: 'Stanley Kubrick, Arthur C. Clarke', Actors: 'Keir Dullea, Gary Lockwood, William Sylvester', Plot: 'After discovering a mysterious artifact buried beneath the Lunar surface, mankind sets off on a quest to find its origins with help from intelligent supercomputer H.A.L. 9000.', Language: 'English', Country: 'UK, USA', Awards: 'Won 1 Oscar. 14 wins & 13 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BNjU0NDFkMTQtZWY5OS00MmZhLTg3Y2QtZmJhMzMzMWYyYjc2XkEyXkFqcGc@._V1_SX300.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.3/10' }], Metascore: '90', imdbRating: '8.3', imdbVotes: '700,000', Type: 'movie' },
  { id: 'tt0078748', imdbID: 'tt0078748', Title: 'Alien', Year: '1979', Rated: 'R', Released: '22 Jun 1979', Runtime: '117 min', Genre: 'Horror, Sci-Fi', Director: 'Ridley Scott', Writer: 'Dan O\'Bannon, Ronald Shusett', Actors: 'Sigourney Weaver, Tom Skerritt, John Hurt', Plot: 'After investigating a mysterious transmission of unknown origin, the crew of a commercial spacecraft encounters a deadly lifeform.', Language: 'English', Country: 'UK, USA', Awards: 'Won 1 Oscar. 19 wins & 23 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BN2NhMDk2MmEtZDQzOC00MmY5LThhYzAtMDdjZGFjOGZjMjdjXkEyXkFqcGc@._V1_QL75_UX380_CR0,6,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.5/10' }], Metascore: '89', imdbRating: '8.5', imdbVotes: '950,000', Type: 'movie' },
  { id: 'tt0082971', imdbID: 'tt0082971', Title: 'Indiana Jones and the Raiders of the Lost Ark', Year: '1981', Rated: 'PG', Released: '12 Jun 1981', Runtime: '118 min', Genre: 'Action, Adventure', Director: 'Steven Spielberg', Writer: 'Lawrence Kasdan, George Lucas, Philip Kaufman', Actors: 'Harrison Ford, Karen Allen, Paul Freeman', Plot: "Archaeologist and adventurer Indiana Jones is hired by the U.S. government to find the Ark of the Covenant before Adolf Hitler's Nazis can obtain its awesome powers.", Language: 'English', Country: 'USA', Awards: 'Won 4 Oscars. 34 wins & 31 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BOGNhMjg2ZjgtYzk4Ni00MTViLTg1MmUtYzM2MDZiYjZlMmU3XkEyXkFqcGc@._V1_SX300.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.4/10' }], Metascore: '85', imdbRating: '8.4', imdbVotes: '1,100,000', Type: 'movie' },
  { id: 'tt0102926', imdbID: 'tt0102926', Title: 'The Silence of the Lambs', Year: '1991', Rated: 'R', Released: '14 Feb 1991', Runtime: '118 min', Genre: 'Crime, Drama, Thriller', Director: 'Jonathan Demme', Writer: 'Thomas Harris, Ted Tally', Actors: 'Jodie Foster, Anthony Hopkins, Lawrence Fishburne', Plot: 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer.', Language: 'English', Country: 'USA', Awards: 'Won 5 Oscars. 51 wins & 52 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BNDdhOGJhYzctYzYwZC00YmI2LWI0MjctYjg4ODdlMDExYjBlXkEyXkFqcGc@._V1_QL75_UY562_CR1,0,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.6/10' }], Metascore: '95', imdbRating: '8.6', imdbVotes: '1,600,000', Type: 'movie' },
  { id: 'tt0120815', imdbID: 'tt0120815', Title: 'Saving Private Ryan', Year: '1998', Rated: 'R', Released: '24 Jul 1998', Runtime: '169 min', Genre: 'Drama, War', Director: 'Steven Spielberg', Writer: 'Robert Rodat', Actors: 'Tom Hanks, Matt Damon, Tom Sizemore', Plot: 'Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines to retrieve a paratrooper whose brothers have been killed in action.', Language: 'English', Country: 'USA', Awards: 'Won 5 Oscars. 75 wins & 77 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BZGZhZGQ1ZWUtZTZjYS00MDJhLWFkYjctN2ZlYjE5NWYwZDM2XkEyXkFqcGc@._V1_QL75_UY562_CR1,0,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.6/10' }], Metascore: '91', imdbRating: '8.6', imdbVotes: '1,500,000', Type: 'movie' },
  { id: 'tt0109830', imdbID: 'tt0109830', Title: 'Forrest Gump', Year: '1994', Rated: 'PG-13', Released: '06 Jul 1994', Runtime: '142 min', Genre: 'Drama, Romance', Director: 'Robert Zemeckis', Writer: 'Winston Groom, Eric Roth', Actors: 'Tom Hanks, Robin Wright, Gary Sinise', Plot: 'The history of the United States from the 1950s to the 1970s through the eyes of an Alabama man with an IQ of 75, who yearns to be reunited with his childhood sweetheart.', Language: 'English', Country: 'USA', Awards: 'Won 6 Oscars. 44 wins & 41 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BNDYwNzVjMTItZmU5YS00YjQ5LTljYjgtMjY2NDVmYWMyNWFmXkEyXkFqcGc@._V1_QL75_UY562_CR4,0,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.8/10' }], Metascore: '82', imdbRating: '8.8', imdbVotes: '2,200,000', Type: 'movie' },
  { id: 'tt0050083', imdbID: 'tt0050083', Title: '12 Angry Men', Year: '1957', Rated: 'Approved', Released: '10 Apr 1957', Runtime: '96 min', Genre: 'Crime, Drama', Director: 'Sidney Lumet', Writer: 'Reginald Rose', Actors: 'Henry Fonda, Lee J. Cobb, Martin Balsam', Plot: 'The defense and the prosecution have rested, and the jury is filing into the jury room to decide if a young Spanish-American is guilty or innocent of murdering his father.', Language: 'English', Country: 'USA', Awards: 'Nominated for 3 Oscars. 16 wins & 11 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BYjE4NzdmOTYtYjc5Yi00YzBiLWEzNDEtNTgxZGQ2MWVkN2NiXkEyXkFqcGc@._V1_QL75_UX380_CR0,11,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '9.0/10' }], Metascore: '97', imdbRating: '9.0', imdbVotes: '850,000', Type: 'movie' },
  { id: 'tt0034583', imdbID: 'tt0034583', Title: 'Casablanca', Year: '1942', Rated: 'PG', Released: '23 Nov 1942', Runtime: '102 min', Genre: 'Drama, Romance, War', Director: 'Michael Curtiz', Writer: 'Julius J. Epstein, Philip G. Epstein, Howard Koch', Actors: 'Humphrey Bogart, Ingrid Bergman, Paul Henreid', Plot: 'A cynical expatriate American cafe owner struggles to decide whether or not to help his former lover and her fugitive husband escape the Nazis in French Morocco.', Language: 'English, French, German, Italian', Country: 'USA', Awards: 'Won 3 Oscars. 6 wins & 6 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BNWEzN2U1YTYtYTQyMS00NTVkLWE2NGQtZWFlMmM0MDNjMmRiXkEyXkFqcGc@._V1_QL75_UX380_CR0,5,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.5/10' }], Metascore: '100', imdbRating: '8.5', imdbVotes: '580,000', Type: 'movie' },
  { id: 'tt0064116', imdbID: 'tt0064116', Title: 'Once Upon a Time in the West', Year: '1968', Rated: 'PG-13', Released: '21 Dec 1968', Runtime: '165 min', Genre: 'Western', Director: 'Sergio Leone', Writer: 'Sergio Leone, Sergio Donati', Actors: 'Henry Fonda, Charles Bronson, Claudia Cardinale', Plot: 'A mysterious woman with a harmonica embarks on a journey of vengeance against a ruthless gun runner and his henchmen.', Language: 'English, Italian', Country: 'Italy, USA', Awards: '6 wins & 7 nominations', Poster: 'https://m.media-amazon.com/images/M/MV5BZjYyNGY1MDEtN2I1MC00MGVhLTljZTYtODQ1NzQ0ODc2NzZlXkEyXkFqcGc@._V1_QL75_UX380_CR0,3,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.5/10' }], Metascore: '80', imdbRating: '8.5', imdbVotes: '360,000', Type: 'movie' },
  { id: 'tt0114709', imdbID: 'tt0114709', Title: 'Toy Story', Year: '1995', Rated: 'G', Released: '22 Nov 1995', Runtime: '81 min', Genre: 'Animation, Adventure, Comedy', Director: 'John Lasseter', Writer: 'John Lasseter, Pete Docter, Andrew Stanton', Actors: 'Tom Hanks, Tim Allen, Don Rickles', Plot: "A cowboy doll is profoundly threatened and jealous when a new spaceman figure supplants him as top toy in a boy's bedroom.", Language: 'English', Country: 'USA', Awards: 'Special Achievement Award. 23 wins & 17 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BZTA3OWVjOWItNjE1NS00NzZiLWE1MjgtZDZhMWI1ZTlkNzYwXkEyXkFqcGc@._V1_SX300.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.3/10' }], Metascore: '96', imdbRating: '8.3', imdbVotes: '1,100,000', Type: 'movie' },
  { id: 'tt0110413', imdbID: 'tt0110413', Title: 'Leon: The Professional', Year: '1994', Rated: 'R', Released: '18 Nov 1994', Runtime: '110 min', Genre: 'Action, Crime, Drama', Director: 'Luc Besson', Writer: 'Luc Besson', Actors: 'Jean Reno, Gary Oldman, Natalie Portman', Plot: "Mathilda, a 12-year-old girl, is reluctantly taken in by Léon, a professional assassin, after her family is murdered. Léon and Mathilda form an unusual bond as they develop a reciprocal relationship.", Language: 'English, Italian, French', Country: 'France', Awards: '12 wins & 16 nominations', Poster: 'https://m.media-amazon.com/images/M/MV5BNGRkYTNhOWQtYmI0Ni00MjZhLWJmMzAtMTA2Mjg4NGNiNDU0XkEyXkFqcGc@._V1_QL75_UX380_CR0,2,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.5/10' }], Metascore: '64', imdbRating: '8.5', imdbVotes: '1,200,000', Type: 'movie' },
  { id: 'tt0118799', imdbID: 'tt0118799', Title: 'Life Is Beautiful', Year: '1997', Rated: 'PG-13', Released: '25 Dec 1997', Runtime: '116 min', Genre: 'Comedy, Drama, Romance', Director: 'Roberto Benigni', Writer: 'Vincenzo Cerami, Roberto Benigni', Actors: 'Roberto Benigni, Nicoletta Braschi, Giorgio Cantarini', Plot: 'When an open-minded Jewish waiter and his son become victims of the Holocaust, he uses a perfect mixture of will, humor, and imagination to protect his son from the dangers around their camp.', Language: 'Italian, German, English', Country: 'Italy', Awards: 'Won 3 Oscars. 69 wins & 54 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BZTBhOGYzZjQtYzE0Mi00MGIwLWE0MWYtNzMxNTM2OTFkM2NjXkEyXkFqcGc@._V1_QL75_UX380_CR0,2,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.6/10' }], Metascore: '59', imdbRating: '8.6', imdbVotes: '750,000', Type: 'movie' },
  { id: 'tt0099685', imdbID: 'tt0099685', Title: 'Goodfellas', Year: '1990', Rated: 'R', Released: '19 Sep 1990', Runtime: '145 min', Genre: 'Biography, Crime, Drama', Director: 'Martin Scorsese', Writer: 'Nicholas Pileggi, Martin Scorsese', Actors: 'Robert De Niro, Ray Liotta, Joe Pesci', Plot: 'The story of Henry Hill and his life in the mob, covering his relationship with his wife and his mob partners Jimmy Conway and Tommy DeVito.', Language: 'English', Country: 'USA', Awards: 'Won 1 Oscar. 35 wins & 29 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BN2E5NzI2ZGMtY2VjNi00YTRjLWI1MDUtZGY5OWU1MWJjZjRjXkEyXkFqcGc@._V1_QL75_UX380_CR0,3,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.7/10' }], Metascore: '90', imdbRating: '8.7', imdbVotes: '1,200,000', Type: 'movie' },
  { id: 'tt0169547', imdbID: 'tt0169547', Title: 'American Beauty', Year: '1999', Rated: 'R', Released: '01 Oct 1999', Runtime: '122 min', Genre: 'Drama', Director: 'Sam Mendes', Writer: 'Alan Ball', Actors: 'Kevin Spacey, Annette Bening, Thora Birch', Plot: 'A sexually frustrated suburban father has a mid-life crisis after becoming infatuated with his daughter\'s teenage best friend.', Language: 'English', Country: 'USA', Awards: 'Won 5 Oscars. 87 wins & 67 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BMDI1MDE0OTMtMmI2MS00Yjc2LTg2MTItMWExYTg5NzA1OGUzXkEyXkFqcGc@._V1_SX300.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.3/10' }], Metascore: '84', imdbRating: '8.3', imdbVotes: '1,200,000', Type: 'movie' },
  { id: 'tt0088763', imdbID: 'tt0088763', Title: 'Back to the Future', Year: '1985', Rated: 'PG', Released: '03 Jul 1985', Runtime: '116 min', Genre: 'Adventure, Comedy, Sci-Fi', Director: 'Robert Zemeckis', Writer: 'Robert Zemeckis, Bob Gale', Actors: 'Michael J. Fox, Christopher Lloyd, Lea Thompson', Plot: 'Marty McFly, a 17-year-old high school student, is accidentally sent thirty years into the past in a time-traveling DeLorean built by his close friend, the eccentric scientist Doc Brown.', Language: 'English', Country: 'USA', Awards: 'Won 1 Oscar. 20 wins & 25 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BZmM3ZjE0NzctNjBiOC00MDZmLTgzMTUtNGVlOWFlOTNiZDJiXkEyXkFqcGc@._V1_QL75_UX380_CR0,14,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.5/10' }], Metascore: '87', imdbRating: '8.5', imdbVotes: '1,300,000', Type: 'movie' },
  { id: 'tt0120586', imdbID: 'tt0120586', Title: 'Good Will Hunting', Year: '1997', Rated: 'R', Released: '05 Dec 1997', Runtime: '126 min', Genre: 'Drama, Romance', Director: 'Gus Van Sant', Writer: 'Matt Damon, Ben Affleck', Actors: 'Robin Williams, Matt Damon, Ben Affleck', Plot: 'Will Hunting, a janitor at M.I.T., has a gift for mathematics but needs help from a psychologist to find direction in his life.', Language: 'English', Country: 'USA', Awards: 'Won 2 Oscars. 23 wins & 35 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BMzhiOTQ0NDItOTg0Zi00OGVmLWE0OGEtMTI4NDM0NWMxZWU4XkEyXkFqcGc@._V1_QL75_UX380_CR0,1,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.3/10' }], Metascore: '70', imdbRating: '8.3', imdbVotes: '1,200,000', Type: 'movie' },
  { id: 'tt0073486', imdbID: 'tt0073486', Title: 'One Flew Over the Cuckoo\'s Nest', Year: '1975', Rated: 'R', Released: '19 Nov 1975', Runtime: '133 min', Genre: 'Comedy, Drama', Director: 'Milos Forman', Writer: 'Lawrence Hauben, Bo Goldman, Ken Kesey', Actors: 'Jack Nicholson, Louise Fletcher, Michael Berryman', Plot: 'A pleasurable mental patient rebels against a tyrannical nurse in a psychiatric ward.', Language: 'English', Country: 'USA', Awards: 'Won 5 Oscars. 31 wins & 15 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BZjA0OWVhMjUtOGRiNy00ZjY0LThkMGEtYWEzZGE0NjA0Yjk2XkEyXkFqcGc@._V1_SX300.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.7/10' }], Metascore: '83', imdbRating: '8.7', imdbVotes: '1,100,000', Type: 'movie' },
  { id: 'tt0047478', imdbID: 'tt0047478', Title: 'Seven Samurai', Year: '1954', Rated: 'Not Rated', Released: '07 May 1956', Runtime: '207 min', Genre: 'Action, Adventure, Drama', Director: 'Akira Kurosawa', Writer: 'Akira Kurosawa, Shinobu Hashimoto, Hideo Oguni', Actors: 'Toshiro Mifune, Takashi Shimura, Keiko Tsushima', Plot: 'A poor village under attack by bandits recruits seven unemployed samurai to help them defend themselves.', Language: 'Japanese', Country: 'Japan', Awards: '2 wins & 3 nominations', Poster: 'https://m.media-amazon.com/images/M/MV5BZjliMWExOTMtZDQ3ZS00NWU3LWIyN2EtMjllNzk3ZTNlYzg4XkEyXkFqcGc@._V1_SX300.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.6/10' }], Metascore: '98', imdbRating: '8.6', imdbVotes: '360,000', Type: 'movie' },
  { id: 'tt0114814', imdbID: 'tt0114814', Title: 'Se7en', Year: '1995', Rated: 'R', Released: '22 Sep 1995', Runtime: '127 min', Genre: 'Crime, Drama, Mystery', Director: 'David Fincher', Writer: 'Andrew Kevin Walker', Actors: 'Brad Pitt, Morgan Freeman, Kevin Spacey', Plot: 'Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.', Language: 'English', Country: 'USA', Awards: 'Nominated for 1 Oscar. 17 wins & 20 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BOTE5MDUxZDUtZWZmZC00NDVmLWFhOGQtNWI2YTc4NzY3MGQ0XkEyXkFqcGc@._V1_QL75_UX380_CR0,2,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.6/10' }], Metascore: '65', imdbRating: '8.6', imdbVotes: '1,800,000', Type: 'movie' },
  { id: 'tt0095016', imdbID: 'tt0095016', Title: 'Die Hard', Year: '1988', Rated: 'R', Released: '20 Jul 1988', Runtime: '132 min', Genre: 'Action, Thriller', Director: 'John McTiernan', Writer: 'Jeb Stuart, Steven E. de Souza', Actors: 'Bruce Willis, Alan Rickman, Bonnie Bedelia', Plot: 'An NYPD officer tries to save his wife and several others taken hostage by German terrorists during a Christmas party at the Nakatomi Plaza in Los Angeles.', Language: 'English', Country: 'USA', Awards: 'Nominated for 4 Oscars. 8 wins & 8 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BMGNlYmM1NmQtYWExMS00NmRjLTg5ZmEtMmYyYzJkMzljYWMxXkEyXkFqcGc@._V1_SX300.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.2/10' }], Metascore: '70', imdbRating: '8.2', imdbVotes: '900,000', Type: 'movie' },
  { id: 'tt0097576', imdbID: 'tt0097576', Title: 'Indiana Jones and the Last Crusade', Year: '1989', Rated: 'PG-13', Released: '24 May 1989', Runtime: '127 min', Genre: 'Action, Adventure', Director: 'Steven Spielberg', Writer: 'Jeffrey Boam, Tom Stoppard, George Lucas', Actors: 'Harrison Ford, Sean Connery, Alison Doody', Plot: "In 1938, after his father Professor Henry Jones, Sr. goes missing while pursuing the Holy Grail, Dr. Henry 'Indiana' Jones, Jr. finds himself up against the Nazis again.", Language: 'English', Country: 'USA', Awards: 'Won 1 Oscar. 17 wins & 21 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BNGIxNzQ0YzYtMjNmYi00YjBlLWFjNzEtNGE3ZGFmYTczM2MwXkEyXkFqcGc@._V1_SX300.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.2/10' }], Metascore: '65', imdbRating: '8.2', imdbVotes: '850,000', Type: 'movie' },
  { id: 'tt0317705', imdbID: 'tt0317705', Title: 'The Incredibles', Year: '2004', Rated: 'PG', Released: '05 Nov 2004', Runtime: '115 min', Genre: 'Animation, Action, Adventure', Director: 'Brad Bird', Writer: 'Brad Bird', Actors: 'Craig T. Nelson, Holly Hunter, Samuel L. Jackson', Plot: 'A family of superheroes, forced to hide their powers, is called back into action to save the world from a vengeful fan-turned-villain.', Language: 'English', Country: 'USA', Awards: 'Won 2 Oscars. 57 wins & 47 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BMTY5OTU0OTc2NV5BMl5BanBnXkFtZTcwMzU4MDcyMQ@@._V1_SX300.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.0/10' }], Metascore: '90', imdbRating: '8.0', imdbVotes: '800,000', Type: 'movie' },
  { id: 'tt0093058', imdbID: 'tt0093058', Title: 'Full Metal Jacket', Year: '1987', Rated: 'R', Released: '10 Jul 1987', Runtime: '116 min', Genre: 'Drama, War', Director: 'Stanley Kubrick', Writer: 'Gustav Hasford, Michael Herr, Stanley Kubrick', Actors: 'Matthew Modine, R. Lee Ermey, Vincent D\'Onofrio', Plot: 'A pragmatic U.S. Marine observes the dehumanizing effects the Vietnam War has on his fellow recruits from their brutal boot camp training to the bloody street fighting in Hue.', Language: 'English', Country: 'USA, UK', Awards: 'Nominated for 1 Oscar. 4 wins & 10 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BYWUzNzZkNzUtNDdiYy00Nzk5LTgxMmItNTk0MjRjNjdjNDA0XkEyXkFqcGc@._V1_QL75_UX380_CR0,4,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.3/10' }], Metascore: '76', imdbRating: '8.3', imdbVotes: '800,000', Type: 'movie' },
  { id: 'tt0056592', imdbID: 'tt0056592', Title: 'To Kill a Mockingbird', Year: '1962', Rated: 'PG', Released: '16 Mar 1963', Runtime: '129 min', Genre: 'Crime, Drama', Director: 'Robert Mulligan', Writer: 'Harper Lee, Horton Foote', Actors: 'Gregory Peck, John Megna, Frank Overton', Plot: 'A lawyer in the Depression-era South defends a black man accused of a terrible crime against a white woman.', Language: 'English', Country: 'USA', Awards: 'Won 1 Oscar. 15 wins & 19 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BZTlkYWU4MGEtZmQyYi00OWEzLTgzY2EtYzVjOTEzYzAyNTk1XkEyXkFqcGc@._V1_SX300.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.3/10' }], Metascore: '87', imdbRating: '8.3', imdbVotes: '320,000', Type: 'movie' },
  { id: 'tt0032553', imdbID: 'tt0032553', Title: 'The Great Dictator', Year: '1940', Rated: 'G', Released: '07 Mar 1941', Runtime: '125 min', Genre: 'Comedy, Drama, War', Director: 'Charlie Chaplin', Writer: 'Charlie Chaplin', Actors: 'Charles Chaplin, Paulette Goddard, Jack Oakie', Plot: 'A dictator of a fictional country discovers that a Jewish barber is his doppelgänger.', Language: 'English', Country: 'USA', Awards: 'Nominated for 5 Oscars. 4 wins & 7 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BMjc4ZjEwNDUtMjlmZS00NzQ4LTg2N2MtMGI3ZjMyMmM3ZDM2XkEyXkFqcGc@._V1_SX300.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.4/10' }], Metascore: '90', imdbRating: '8.4', imdbVotes: '250,000', Type: 'movie' },
  { id: 'tt0105695', imdbID: 'tt0105695', Title: 'Unforgiven', Year: '1992', Rated: 'R', Released: '07 Aug 1992', Runtime: '130 min', Genre: 'Drama, Western', Director: 'Clint Eastwood', Writer: 'David Webb Peoples', Actors: 'Clint Eastwood, Gene Hackman, Morgan Freeman', Plot: 'Retired Old West gunslinger William Munny reluctantly takes on one last job, with the help of his old partner Ned Logan and a young gun-wielding Billy the Kid.', Language: 'English', Country: 'USA', Awards: 'Won 4 Oscars. 39 wins & 31 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BNmZmMzM3YWMtZjg5Yi00M2MxLTg3ZGItNGU4YjQxNDAxM2Q4XkEyXkFqcGc@._V1_SX300.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.2/10' }], Metascore: '85', imdbRating: '8.2', imdbVotes: '430,000', Type: 'movie' },
  { id: 'tt0078788', imdbID: 'tt0078788', Title: 'Apocalypse Now', Year: '1979', Rated: 'R', Released: '15 Aug 1979', Runtime: '147 min', Genre: 'Drama, Music, War', Director: 'Francis Ford Coppola', Writer: 'John Milius, Francis Ford Coppola', Actors: 'Martin Sheen, Marlon Brando, Robert Duvall', Plot: 'A U.S. Army officer serving in Vietnam is assigned to assassinate a renegade Special Forces Colonel who sees himself as a god.', Language: 'English, French, Vietnamese', Country: 'USA', Awards: 'Won 2 Oscars. 21 wins & 33 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BZDhiMTljYjYtODc1Yy00MmEwLTg2OTYtYmE1YTRmNDE4MmEwXkEyXkFqcGc@._V1_QL75_UX380_CR0,11,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.4/10' }], Metascore: '90', imdbRating: '8.4', imdbVotes: '700,000', Type: 'movie' },

  // === HORROR ===
  { id: 'tt0081505', imdbID: 'tt0081505', Title: 'The Shining', Year: '1980', Rated: 'R', Released: '23 May 1980', Runtime: '146 min', Genre: 'Drama, Horror', Director: 'Stanley Kubrick', Writer: 'Stephen King, Stanley Kubrick', Actors: 'Jack Nicholson, Shelley Duvall, Danny Lloyd', Plot: 'A family heads to an isolated hotel for the winter where a sinister presence drives the father into madness, while his young son precognitives sees the evil.', Language: 'English', Country: 'UK, USA', Awards: '2 wins & 4 nominations', Poster: 'https://m.media-amazon.com/images/M/MV5BNmM5ZThhY2ItOGRjOS00NzZiLWEwYTItNDgyMjFkOTgxMmRiXkEyXkFqcGc@._V1_SX300.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.4/10' }], Metascore: '63', imdbRating: '8.4', imdbVotes: '1,100,000', Type: 'movie' },
  { id: 'tt0038650', imdbID: 'tt0038650', Title: 'It\'s a Wonderful Life', Year: '1946', Rated: 'PG', Released: '07 Jan 1947', Runtime: '130 min', Genre: 'Drama, Family, Fantasy', Director: 'Frank Capra', Writer: 'Frances Goodrich, Albert Hackett, Frank Capra', Actors: 'James Stewart, Donna Reed, Lionel Barrymore', Plot: 'An angel is sent from Heaven to help a desperately frustrated businessman by showing him what life would have been like if he had never existed.', Language: 'English', Country: 'USA', Awards: 'Nominated for 5 Oscars. 6 wins & 6 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BZjc4NDZhZWMtNGEzYS00ZWU2LThlM2ItNTA0YzQ0OTExMTE2XkEyXkFqcGc@._V1_SX300.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.6/10' }], Metascore: '88', imdbRating: '8.6', imdbVotes: '480,000', Type: 'movie' },
  // === ROMANCE ===

  // === COMEDY ===

  // === MORE ACTION/ADVENTURE ===
  { id: 'tt1241982', imdbID: 'tt1241982', Title: 'Blade (2025)', Year: '2025', Rated: 'R', Released: '07 Nov 2025', Runtime: 'TBD', Genre: 'Action, Horror, Sci-Fi', Director: 'Yann Demange', Writer: 'Michael Starrbury, Stacy Osei-Kuffour', Actors: 'Mahershala Ali, Aaron Pierre, Mia Goth', Plot: 'A reboot of the Marvel vampire hunter franchise. Blade, a half-human, half-vampire, wages a secret war against the vampires who destroyed his mother.', Language: 'English', Country: 'USA', Awards: 'N/A', Poster: 'https://m.media-amazon.com/images/M/MV5BMTkzNjc1ODktMzllMi00NWM3LWE0NjItMjIxYjUxZWU4NjI4XkEyXkFqcGc@._V1_SX300.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '0/10' }], Metascore: '0', imdbRating: '0', imdbVotes: '0', Type: 'movie' },
  { id: 'tt9603212', imdbID: 'tt9603212', Title: 'Mission: Impossible 8', Year: '2025', Rated: 'PG-13', Released: '23 May 2025', Runtime: 'TBD', Genre: 'Action, Adventure', Director: 'Christopher McQuarrie', Writer: 'Christopher McQuarrie, Erik Jendresen', Actors: 'Tom Cruise, Hayley Atwell, Simon Pegg', Plot: 'Ethan Hunt faces his most dangerous mission yet as a global threat emerges that endangers all of humanity.', Language: 'English', Country: 'USA', Awards: 'N/A', Poster: 'https://m.media-amazon.com/images/M/MV5BN2U4OTdmM2QtZTkxYy00ZmQyLTg2N2UtMDdmMGJmNDhlZDU1XkEyXkFqcGc@._V1_QL75_UY562_CR1,0,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '0/10' }], Metascore: '0', imdbRating: '0', imdbVotes: '0', Type: 'movie' },
  { id: 'tt6263850', imdbID: 'tt6263850', Title: 'Deadpool & Wolverine', Year: '2024', Rated: 'R', Released: '26 Jul 2024', Runtime: '128 min', Genre: 'Action, Comedy, Sci-Fi', Director: 'Shawn Levy', Writer: 'Rhett Reese, Paul Wernick, Zeb Wells', Actors: 'Ryan Reynolds, Hugh Jackman, Emma Corrin', Plot: 'Deadpool is recruited by the TVA to save his world from extinction alongside a reluctant Wolverine.', Language: 'English', Country: 'USA', Awards: 'Nominated for 2 Oscars. 15 wins & 43 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BZTk5ODY0MmQtMzA3Ni00NGY1LThiYzItZThiNjFiNDM4MTM3XkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '7.7/10' }], Metascore: '55', imdbRating: '7.7', imdbVotes: '550,000', Type: 'movie' },
  { id: 'tt15239678', imdbID: 'tt15239678', Title: 'Dune: Part Two', Year: '2024', Rated: 'PG-13', Released: '01 Mar 2024', Runtime: '166 min', Genre: 'Action, Adventure, Drama', Director: 'Denis Villeneuve', Writer: 'Denis Villeneuve, Jon Spaihts, Frank Herbert', Actors: 'Timothée Chalamet, Zendaya, Austin Butler', Plot: 'Paul Atreides unites with the Fremen while on a warpath of revenge against the conspirators who destroyed his family.', Language: 'English', Country: 'USA, Canada', Awards: 'Won 1 Oscar. 96 wins & 194 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BNTc0YmQxMjEtODI5MC00NjFiLTlkMWUtOGQ5NjFmYWUyZGJhXkEyXkFqcGc@._V1_QL75_UX380_CR0,0,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.5/10' }], Metascore: '79', imdbRating: '8.5', imdbVotes: '850,000', Type: 'movie' },

  // === MORE CLASSICS ===
  { id: 'tt0060161', imdbID: 'tt0060161', Title: 'The Good, the Bad and the Ugly', Year: '1966', Rated: 'R', Released: '15 Dec 1966', Runtime: '178 min', Genre: 'Adventure, Western', Director: 'Sergio Leone', Writer: 'Age & Scarpelli, Luciano Vincenzoni, Sergio Leone', Actors: 'Clint Eastwood, Eli Wallach, Lee Van Cleef', Plot: 'While the Civil War rages between the Union and the Confederacy, three men – a bounty hunter, a bandit, and a con artist – search for a fortune in gold buried in a remote cemetery.', Language: 'English, Italian', Country: 'Italy, Spain, West Germany, USA', Awards: '4 wins & 5 nominations', Poster: 'https://m.media-amazon.com/images/M/MV5BY2JlYjcwNTEtNGMyOS00OTgzLWFhYWUtZDgxYzI1OTk3ZDFkXkEyXkFqcGc@._V1_SX300.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.8/10' }], Metascore: '90', imdbRating: '8.8', imdbVotes: '780,000', Type: 'movie' },
  { id: 'tt0118715', imdbID: 'tt0118715', Title: 'The Big Lebowski', Year: '1998', Rated: 'R', Released: '06 Mar 1998', Runtime: '117 min', Genre: 'Comedy, Crime', Director: 'Joel Coen, Ethan Coen', Writer: 'Ethan Coen, Joel Coen', Actors: 'Jeff Bridges, John Goodman, Julianne Moore', Plot: 'Jeff \"The Dude\" Lebowski is mistaken for a millionaire, and two thugs urinate on his rug. The Dude embarks on a bizarre journey to seek restitution.', Language: 'English', Country: 'USA, UK', Awards: 'Nominated for 2 Oscars. 15 wins & 16 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BY2E3OWQ5OWYtYTRkMC00NjVjLWIzZDQtNmRmM2ZiYTIyYmYxXkEyXkFqcGc@._V1_SX300.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.1/10' }], Metascore: '71', imdbRating: '8.1', imdbVotes: '620,000', Type: 'movie' },
  { id: 'tt0120685', imdbID: 'tt0120685', Title: 'Goodfellas', Year: '1990', Rated: 'R', Released: '19 Sep 1990', Runtime: '145 min', Genre: 'Biography, Crime, Drama', Director: 'Martin Scorsese', Writer: 'Nicholas Pileggi, Martin Scorsese', Actors: 'Robert De Niro, Ray Liotta, Joe Pesci', Plot: 'The story of Henry Hill and his life in the mob, covering his relationship with his wife and his mob partners Jimmy Conway and Tommy DeVito.', Language: 'English', Country: 'USA', Awards: 'Won 1 Oscar. 35 wins & 29 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BMzdmYmUzYjAtMmJhNi00NGU3LWJiODYtM2I5MGFhZjBhM2NhXkEyXkFqcGc@._V1_SX300.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.7/10' }], Metascore: '90', imdbRating: '8.7', imdbVotes: '1,200,000', Type: 'movie' },
  { id: 'tt0038650', imdbID: 'tt0038650b', Title: 'Singin\' in the Rain', Year: '1952', Rated: 'G', Released: '11 Mar 1952', Runtime: '103 min', Genre: 'Comedy, Musical, Romance', Director: 'Stanley Donen, Gene Kelly', Writer: 'Betty Comden, Adolph Green', Actors: 'Gene Kelly, Donald O\'Connor, Debbie Reynolds', Plot: 'A silent film star falls for a chorus girl just as he and his studio must cope with the transition to talking pictures.', Language: 'English', Country: 'USA', Awards: 'Nominated for 2 Oscars. 5 wins & 6 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BZmE0MGJhNmYtOWNjYi00Njc5LWE2YjEtMWMxZTVmODUwMmMxXkEyXkFqcGc@._V1_SX300.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.3/10' }], Metascore: '94', imdbRating: '8.3', imdbVotes: '400,000', Type: 'movie' },
  { id: 'tt0054215', imdbID: 'tt0054215', Title: 'Psycho', Year: '1960', Rated: 'R', Released: '16 Sep 1960', Runtime: '109 min', Genre: 'Horror, Mystery, Thriller', Director: 'Alfred Hitchcock', Writer: 'Joseph Stefano, Robert Bloch', Actors: 'Anthony Perkins, Janet Leigh, Vera Miles', Plot: 'A Phoenix secretary embezzles $40,000 from her employer\'s client, goes on the run, and checks into a remote motel run by a young man under the domination of his mother.', Language: 'English', Country: 'USA', Awards: 'Nominated for 4 Oscars. 7 wins & 10 nominations total', Poster: 'https://m.media-amazon.com/images/M/MV5BYjZhMzFiZjItODA3ZC00MmRhLWIzMGYtMmVjOWUwYTA3MTRjXkEyXkFqcGc@._V1_QL75_UX380_CR0,1,380,562_.jpg', Ratings: [{ Source: 'Internet Movie Database', Value: '8.5/10' }], Metascore: '97', imdbRating: '8.5', imdbVotes: '650,000', Type: 'movie' },

];
